### ISSUE TITLE
Testing errors after building LiSA

### ISSUE THREAD

**Issue by WilliamWangPeng** [gaetanserre/LiSA#1]
HI dear experts,  
    Honor to write a letter to you, I met this error, do you know how to solve this?

![image](https://user-images.githubusercontent.com/51076736/112967946-5ef5b580-917e-11eb-8a04-d7dbfda1c476.png)

thank you  
best regards  
William

**Comment by gaetanserre** [comment]
Hello,
Thank you very much for your message.
Try these commands:
``
cd out
``
``
./LiSA ../assets/chess_pawn.rto 10 ../test.ppm
``
Normally, you will have the image inside the main folder.

The error is due to the fact that the .obj paths are defined in the .rto files. You have to modify these paths according to how you are going to call them.

However, the dragon and panther scenes are too big to be put on github, so they won't work.
I'll make an update to solve these problems.

Thank you.
Best regards,
Gaëtan
